### ISSUE TITLE
When 3.6.2 is open various versions of 3.7 won't open

### ISSUE THREAD

**Issue by scorster** [Jojo-Schmitz/MuseScore#468] opened 2024-05-07 04:55 UTC
I'm pretty sure I used to run 3.6.2 and 3.7 simultaneously

But since my last update to

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 3.7.0.8734326368, revision: GitHub-Jojo-Schmitz-MuseScore-5eab99e

3.7 won't open if I have 3.6.2 open. 

Nor can I run two versions of 3.7.

**Comment by Jojo-Schmitz** [comment] 2024-05-07 07:28
Works for me, but that might be my personal build/setup only, but indeed not for the GitHub CI artifacts.
Well possible it used to work before I switch the builds to be "Release" rather than "Development"
Actually since the merge of #194, so the change from "unstable" to "Evolution"

**Comment by Jojo-Schmitz** [comment] 2024-05-07 07:29
So I'd rather close this as 'By Design', what's your view here?

**Comment by Jojo-Schmitz** [comment] 2024-05-07 07:43
I've now documented/clarified that in the [Wiki](https://github.com/Jojo-Schmitz/MuseScore/wiki)

**Closed** 2024-05-28 12:28 UTC
Labels: wontfix
