### ISSUE TITLE
Tremolos / articulations screwed up in piano roll editor

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#580] opened 2024-08-19 17:55 UTC
They don't manifest properly (the note events show incorrectly), so whoever touched the PRE code did something more than likely. For example, here's a tremolo:

[tremolo.webm](https://github.com/user-attachments/assets/78c20251-858a-421e-aed7-796f7da3c94c)

Same happens with trill lines. 
Doesn't seem to be a problem with my personal build or 3.6.2 so something happened in here in the past year or so I'd imagine.

**Comment by worldwideweary** [comment] 2024-08-19 18:00
P.S. manifests not in 2023.09.15 build but does in 2024.04.07... so somewhere between there

**Comment by worldwideweary** [comment] 2024-08-19 20:47
Fwiw, it's most likely (just tested and this is the case) b6f52bec84 ("Backporting changes to the piano roll made for MuseScore 4 PR #9109", 2024-01-23) 

Maybe that's #287. As to where exactly is another question

**Comment by worldwideweary** [comment] 2024-08-19 20:49
Slightly confusing, because if i check the commit in 3.x, the changes are different for the mentioned "backporting" on 2024-01-23 coimpared with #287, maybe I'm trippin'

**Comment by worldwideweary** [comment] 2024-08-19 20:51
This is merely a random hunch, but I wouldn't be surprised if 
```cpp 
     //p->setRenderHints(QPainter::Antialiasing | QPainter::SmoothPixmapTransform | QPainter::TextAntialiasing);
      //for (int i = 0; i < _noteList.size(); ++i)
      //      _noteList[i]->paint(p);

      p->setRenderHints(QPainter::Antialiasing | QPainter::SmoothPixmapTransform | QPainter::TextAntialiasing);
      for (PianoItem* block : _noteList) {
            drawNoteBlock(p, block);
            }
```
has something to do with it since it might not be taking into account the tremolo note events or something

**Comment by Jojo-Schmitz** [comment] 2024-08-19 20:56
Back in the day I had askey you to test/verify that PR, but mistyped your nick, so you didn't get notified :-/

@blackears: comments in this?

**Comment by blackears** [comment] 2024-08-19 21:20
I remember doing this but it was a long time ago.  I also uploaded some big changes since then.  Is it still a problem?

**Comment by blackears** [comment] 2024-08-19 21:24
I didn't do any testing with tremolos.  I'm not sure what the issue is here.   What behavior are you expecting?

**Comment by worldwideweary** [comment] 2024-08-19 21:38
Expected behavior: Show the tremolo events as in 3.6.2

Sheet:
![image](https://github.com/user-attachments/assets/ca1b3a69-dd26-4abf-997b-08c21b1825ad)

3.7 Evolution with this implementation:
![image](https://github.com/user-attachments/assets/0b3865ae-413f-4ace-8900-50d05d14fa48)

3.6.2 PRE:
![image](https://github.com/user-attachments/assets/481b16bd-e431-43ee-8296-6facd3c451e5)

**Comment by worldwideweary** [comment] 2024-08-19 21:48
it's probably 
```cpp 
for (NoteEvent& e : note->playEvents()) {
```
in `drawNoteBlock()` because it used to draw from the `_noteList[i]->paint(p)` in pianoview.cpp pianoItem::paint 

playEvents is probably only related to the note and not the "noteEventList" that includes the alterations such as articulations etc...hence the failure to consider the alterations and only use the "notehead" from the score and paint just that

**Comment by blackears** [comment] 2024-08-20 03:11
The issue there is that the actual notes are half notes, not trills.  The PRE is reflecting the notation, not the playback so that it's possible to move the notes around to edit the score.  There is one tool for adjusting playback lengths - I'm not sure if displays notes like this or not. I'm away from home for the next couple of days so I can't check.  But for the other four tools this would be intended behavior.

**Comment by worldwideweary** [comment] 2024-08-20 03:28
Ah! That was the missing piece of information. If "Change Playback Length" is the mode selected, then the sounding events do show rather than the score events. That settles it, so this issue can get closed.
Image verfies:

![image](https://github.com/user-attachments/assets/e4d82533-745b-4850-9c87-90d5c9fd38c4)


Thanks for mentioning the tool!

**Comment by Jojo-Schmitz** [comment] 2024-08-20 07:25
Ok, let's close it then.

**Closed by Jojo-Schmitz** 2024-08-20 07:25 UTC
Labels: bug, regression
