### ISSUE TITLE
Shortcut to increase note or rest duration beyond the measure causes instant crash

### ISSUE THREAD

**Issue by fernandomartin777** [Jojo-Schmitz/MuseScore#359] opened 2024-03-01 23:34 UTC
A bug, not present in previous versions, was somehow introduced in recent buildings of MU3.7.
In other versions, if we select the last note or rest of a measure and press the keyboard shortcut of a longer duration, automatically the same note is generated tied in the next measure.
Example: Suppose in a 4/4 measure we have two half notes, C and D. If we select D and press 7 (shortcut to whole note) automatically another half note D appears in the next measure and already tied to the D at the previous measure.
Now, at the latest appimage builds of MU3.7, whenever I try to do this the program crashes.
It was tested in an up-to-date Kubuntu 23.10 using the appimage version from the latest builds of MU3.7. The bug occurs with both, notes and rests.

**Comment by Jojo-Schmitz** [comment] 2024-03-02 09:10
As mentioned inhttps://musescore.org/en/node/361140 I can't reproduce on Windows

**Comment by fernandomartin777** [comment] 2024-03-02 16:13
Today, just as an experiment, I delete all Musescore files from .config and .local/share, therefore erasing all user configurations and starting with a brand new config solved the issue. It may have been some corrupted configuration or some bug related to configurations that hits too rarely to be noticed.

**Comment by Jojo-Schmitz** [comment] 2024-03-03 10:00
I guess with that we can close the issue. Until someone finds a way to reliably reproduce it

**Comment by Jojo-Schmitz** [comment] 2024-03-04 08:02
See https://musescore.org/en/node/361140#comment-1231635 ff. and https://github.com/Jojo-Schmitz/MuseScore/pull/315#issuecomment-1975502157

**Comment by worldwideweary** [comment] 2024-03-04 08:53
@Jojo-Schmitz I'm not sure, but the *intention* of the patch in 4.x makes sense. I tried a hand at something and will do a PR, instead of just a reversion of the 1-liner

**Comment by Jojo-Schmitz** [comment] 2024-03-04 09:07
This here would prevent the crash:
```cpp
$ git diff
diff --git a/libmscore/cmd.cpp b/libmscore/cmd.cpp
index 5eb6c9ecff..b1c584eeb4 100644
--- a/libmscore/cmd.cpp
+++ b/libmscore/cmd.cpp
@@ -1466,6 +1466,8 @@ void Score::changeCRlen(ChordRest* cr, const Fraction& dstF, bool fillWithRest)
                   break;
             Segment* s = m1->first(SegmentType::ChordRest);
             cr1 = toChordRest(s->element(track));
+            if (!cr1)
+                  continue;
             }
       connectTies();
       }
```
but would still not allow the operation of making a non-vo1ce 1 note longer and crossing a measure boundary

**Comment by fernandomartin777** [comment] 2024-03-04 13:41
> @Jojo-Schmitz I'm not sure, but the _intention_ of the patch in 4.x makes sense. I tried a hand at something and will do a PR, instead of just a reversion of the 1-liner

Before this implementation as we created a 2nd, 3rd or 4rd voice in a way that filled the measure, automatically a new rest was generated at the following measure, what is pointless because the software doesn't know if we have the intention of adding anything else in the following measure. The intention probably was to avoid creating unnecessary rests in the following measures. However when we extend a note BEYOND the measure it's important that the remainig space of THAT measure receive a rest accordingly. It's muco more practical to be able to extend the note duration and if we want delete the rest than creating the a new note in a new measure and tying the previous note to it. That implementation backfired and generated a bug.

**Comment by Jojo-Schmitz** [comment] 2024-03-04 15:00
Sure, and nothing we intend to break.

**Comment by fernandomartin777** [comment] 2024-03-04 16:32
I've just downloaded [https://github.com/Jojo-Schmitz/MuseScore/actions/runs/8138591904](url) and the crash seems to be fixed. Thanks for your good job and nice to see more people joining the 3.7 team.

**Closed** 2024-03-05 22:11 UTC
Labels: bug
