### ISSUE TITLE
Outdated Browser

### ISSUE THREAD

**Issue by Cubiking** [Jojo-Schmitz/MuseScore#716] opened 2024-12-04 20:34 UTC
The embed browser seems to be outdated and thus cannot display musescore.com. Any possibility to update it?

**Comment by Jojo-Schmitz** [comment] 2024-12-04 20:46
It is QWebEngine, part of Qt

**Comment by Cubiking** [comment] 2024-12-04 21:05
I see. I saw qtwebengine.exe in the app folder. Can we simply swap to a newer .exe to update the embed browser?

**Comment by Jojo-Schmitz** [comment] 2024-12-04 21:14
But what makes you think that it is outdated?

**Comment by Jojo-Schmitz** [comment] 2024-12-04 22:01
Hmm, there's no qtwebengine.exe in the app folder of my selfbuild 3.7, build with QtCreatort and MinGW. I guess that's why there "Save online " works, by using Edge?

**Comment by Jojo-Schmitz** [comment] 2024-12-04 22:13
The Artifacts from GitHub CI to have QtWebEndingProcess.exe (from Qt-5.15.2, 3,6.2 had Qt 5.5.9) just crash on an attemps to do a "Save online"
I guess this explains #261 and probably is a duplicate of that

**Comment by Jojo-Schmitz** [comment] 2024-12-05 08:41
Copying the QtWebEndingProcess.exe from 3.6.2 into the bin directory of 3.7 fixes the crash, so no, it is not too old, but too new
I guess reverting 3.7 to use Qt 5.9.9 for the 64-bit builds too should fix this.

I'll close this issue, as being a duplicate of #261

**Closed by Jojo-Schmitz** 2024-12-05 08:41 UTC

**Comment by Cubiking** [comment] 2024-12-06 09:08
Thanks
