### ISSUE TITLE
Hairpins now export as filled in on SVG export (after the polyline update)

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#171] opened 2023-09-15 06:23 UTC
### Issue type

Engraving bug

### Bug description

It's too bad, since it works well for the program and the PDF/PNG export

### Steps to reproduce

Make a score and add a hairpin...
Export to SVG
load it up and notice: 

### Screenshots/Screen recordings

![hairpinSVG outputMS37](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/d368d893-870d-48c7-a69c-da26aa0d1043)

### MuseScore Version

3.7

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

...

### Additional context

I noticed this earlier but forgot to mention it to you here. First pass glance at code didn't make sense as to why this is happening. . . 

Since I export a lot of stuff via SVG... i had to personally revert. Not sure what can be done about it. It's probably something stupid somewhere lying around in the old code :)

**Comment by Jojo-Schmitz** [comment] 2023-09-21 16:01
Can you pinpoint the exact change, the commit? The one you revert?

**Comment by Jojo-Schmitz** [comment] 2023-09-25 13:21
Ah, you mean c8af10449d, don't you?

**Comment by Jojo-Schmitz** [comment] 2023-09-25 14:25
Whatever: I can't reproduce!

**Comment by worldwideweary** [comment] 2023-09-26 10:00
Ah, you're right. I had some coding left-overs doing something wrong.
However, it looks like now 3.7 is using flat caps (i may have suggested that earlier problematically)... and i think that might make hooks etc not "connect" so well:

![joiningproblem](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/cd3aff60-87f6-4cd1-8538-ec8f4a63511b)

8-bit style. I think switching to square caps would fix it. Apologia.

**Comment by worldwideweary** [comment] 2023-09-26 10:12
I'll close this though in the sense of the title. Or maybe could rename it to reflect the problem just mentioned.... What would be optimal here though it seems would be to get polylines to work on hooks that had 45 degree angles to them (45 degree hooks and... pedal line joins. But that'd be some heavier work

**Comment by Jojo-Schmitz** [comment] 2023-09-26 10:51
Please close this and open a new one for that other issue

**Closed** 2023-09-26 11:09 UTC
Labels: bug
