### ISSUE TITLE
Windows, 64-bit: for some users Palettes don't exist at all

### ISSUE THREAD

**Issue by HeinzVo** [Jojo-Schmitz/MuseScore#140] opened 2023-07-24 13:29 UTC
### Issue type

UI bug

### Bug description

MuseScore 3.7 Palettes Menu fail to load in the 64-bit version for Windows. There only is an empty gray field with no content at all (not even the add palettes button).

### Steps to reproduce

1. Start MuseScore 3.7.0 (64-bit Windows version) and load any score sheet
2. Select "View Palettes" or press F9
3. Only an empty gray field appears now with no palette contents

### Screenshots/Screen recordings

![MuseScore 3 (3 7 0 unstable)_NO Palettes and Plugins in Windows x64-Version (1)](https://github.com/Jojo-Schmitz/MuseScore/assets/140117374/8a002a7b-43e0-40df-b815-0baef1f51a15)

### MuseScore Version

3.7.0 (any 64-bit Windows version)

### Regression

Choose option...

### Operating system

Windows 10, 64-bit

### Additional context

Any build of MuseScore 3.7.0, but only 64-bit Windows-Versions (not in x86 Versions).
(Note: Plugins also will not appear in 64-bit Windows versions - may be any dependence)

**Comment by Jojo-Schmitz** [comment] 2023-07-31 08:18
I believe this is a duplicate of #128, in the sennse that it has the same underlying cause

**Comment by HeinzVo** [comment] 2023-07-31 11:11
Probably yes, but very much more critical because with no palettes menu one can do nothing in MuseScore for editing scores...

Is it possible that there might be somewhere a 32-bit-dll instead of a 64-bit one or not registered?

Heinz Vonesch
Im Hang 29
CH-8903 Birmensdorf
Tel.M: +41 76 7474392

[Nachricht gesendet vom Mobiltelefon]

Am 31. Juli 2023 10:18:17 MESZ schrieb Joachim Schmitz ***@***.***>:
I believe this is a duplicate of #128, in the sense that it has the same underlying cause

**Comment by Jojo-Schmitz** [comment] 2023-07-31 11:13
Agreed. Unfortunately this is a problem I cannot reproduce.

**Comment by HeinzVo** [comment] 2023-07-31 16:38
I tried out the 64-bit Version now on a new Windows 11 Computer with the same result:
No Palettes menu and no Plugins!
(Note: the MS3.6.2, 64-bit was also already installed prior here, but no MS4).

It seems to be a global problem for almost all computers (except yours). Could it be, that on yours there is something installed, which usually is not on other peoples computer, so it works on yours? Or is there any problem sharing libraries with 3.6.2 and 3.7.0?

Many Greetings, Heinz

Heinz Vonesch
Im Hang 29
CH-8903 Birmensdorf
Tel.M: +41 76 7474392

[Nachricht gesendet vom Mobiltelefon]

Am 31. Juli 2023 13:13:23 MESZ schrieb Joachim Schmitz ***@***.***>:
Agreed. Unfortunately this is a problem I cannot reproduce.

**Comment by Jojo-Schmitz** [comment] 2023-07-31 16:50
Well. I do have a full development enviromnent installed, so maybe it finds the correct DLL somewhere.

**Comment by Jojo-Schmitz** [comment] 2023-08-07 08:26
All of a sudden I __can__ reproduce it. Dunno why though, nor what the fix is?!?

**Comment by Jojo-Schmitz** [comment] 2023-08-07 09:14
Acrtually I can, if I remove "C:\Qt\5.15.2\msvc2019_64\bin" from my PATH...

**Comment by Jojo-Schmitz** [comment] 2023-08-07 10:08
Pinned it down to Qt5QmlWorkerScript.dll, the only file it does access from "C:\Qt\5.15.2\msvc2019_64\bin" if in PATH...

**Comment by Jojo-Schmitz** [comment] 2023-08-07 10:18
I might have nailed it, see #149

**Comment by Jojo-Schmitz** [comment] 2023-08-07 13:19
Fixed via #149

**Closed by Jojo-Schmitz** 2023-08-07 13:19 UTC
Labels: bug, duplicate
